spring:
  application:
    name: booking-service
  profiles:
    active: local
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      properties:
        retry.backoff.ms: 1000
        spring.json.add.type.headers: false
      topics:
        event-updated: event-updated
    consumer:
      group-id: booking-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: eventticketsystem.booking.dto.EventCreatedMessage
logging:
  level:
    liquibase: INFO